// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1QfNab5bheYqKAZ465QZJSPEPBchviw',
    appId: '1:363870794295:web:a091b6a34a59eb052d05b2',
    messagingSenderId: '363870794295',
    projectId: 'student-da066',
    authDomain: 'student-da066.firebaseapp.com',
    storageBucket: 'student-da066.firebasestorage.app',
    measurementId: 'G-04WK81WKS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qgSTupnM78ih9D-Rtj8xrwX7FNb9S98',
    appId: '1:363870794295:android:f4a72859006e13c82d05b2',
    messagingSenderId: '363870794295',
    projectId: 'student-da066',
    storageBucket: 'student-da066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfojmXo_pm5jZBU58PI7xeTJWu9RnTIvM',
    appId: '1:363870794295:ios:7c9280f73266f54f2d05b2',
    messagingSenderId: '363870794295',
    projectId: 'student-da066',
    storageBucket: 'student-da066.firebasestorage.app',
    iosBundleId: 'com.example.student1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfojmXo_pm5jZBU58PI7xeTJWu9RnTIvM',
    appId: '1:363870794295:ios:7c9280f73266f54f2d05b2',
    messagingSenderId: '363870794295',
    projectId: 'student-da066',
    storageBucket: 'student-da066.firebasestorage.app',
    iosBundleId: 'com.example.student1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1QfNab5bheYqKAZ465QZJSPEPBchviw',
    appId: '1:363870794295:web:bdcf54749e3e2b6a2d05b2',
    messagingSenderId: '363870794295',
    projectId: 'student-da066',
    authDomain: 'student-da066.firebaseapp.com',
    storageBucket: 'student-da066.firebasestorage.app',
    measurementId: 'G-JEDVMS8367',
  );
}
